#footprint: [[-0.1275, -0.24], [-0.1275, 0.02], [0.1275, 0.02], [0.1275, -0.24]]
footprint: [[-0.1, -0.1], [-0.1, 0.1], [0.1, 0.1], [0.1, -0.1]]
footprint_padding: 0.05

robot_base_frame: base_link
#robot_base_frame: laser_frame
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.2

resolution: 0.05

#obstacle_range: 5.5
#raytrace_range: 6.0

obstacle_range: 3.0
raytrace_range: 10.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

inflation:
    inflation_radius: 0.05
